@startuml
!include ../../c4model_puml/C4_Container.puml

Person(personAlias, "Label", "Robert is Cool!")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml
